[directories]
dataset = "Dataset"
preprocessed_data = "Prep_Dataset"
saved_models = "Models"

[audio]
rate = 22050
record_duration = 2
duration = 1
mfcc = 13
hop_length = 512

[data]
2 = ["backward", "bed"]
5 = ["backward", "bed", "bird", "cat", "dog"]
10 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward"]
numbers = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
all = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn", "left", "marvin", "nine", "no", "off", "on", "one", "right", "seven", "sheila", "six", "stop", "three", "tree", "two", "up", "visual", "wow", "yes", "zero"]