[directories]
dataset = "Dataset"
preprocessed_data = "Prep_Dataset"
saved_models = "Models"
temporary_files = "Temp"

[preprocessing]
validation_percentage = 15
testing_percentage = 15
sample_max = 134217727
data_normalization = false

[audio]
rate = 22050
record_duration = 2
prep_duration = 1
mfcc_coefficients = 13
sample_shape = [13, 44, 1]

[ai]
epochs = 40

[data]
2 = ["backward", "bed"]
5 = ["backward", "bed", "bird", "cat", "dog"]
10 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward"]
15 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn"]
19 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn", "left", "marvin", "nine", "no"]
20 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn", "left", "marvin", "nine", "no", "off"]
30 = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn", "left", "marvin", "nine", "no", "off", "on", "one", "right", "seven", "sheila", "six", "stop", "three", "tree", "two"]
numbers = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
all = ["backward", "bed", "bird", "cat", "dog", "down", "eight", "five", "follow", "forward", "four", "go", "happy", "house", "learn", "left", "marvin", "nine", "no", "off", "on", "one", "right", "seven", "sheila", "six", "stop", "three", "tree", "two", "up", "visual", "wow", "yes", "zero"]